name: projetfinal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  intl: ^0.20.1
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.70.2
  provider: ^6.0.0 
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    # Include specific assets if necessary
    # - lib/images/my_image.png
  # Uncomment and define if using custom fonts
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700