// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnaiPY5gRyx_HASt37TyLEbX5U5_6zmWc',
    appId: '1:696358888242:web:c8e9bd546762c7575e6d2b',
    messagingSenderId: '696358888242',
    projectId: 'authapp-f7d36',
    authDomain: 'authapp-f7d36.firebaseapp.com',
    storageBucket: 'authapp-f7d36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBET7XFd0k_YaP9vgsv9QEoqkGJlc-xI',
    appId: '1:696358888242:android:c288119911c1a20f5e6d2b',
    messagingSenderId: '696358888242',
    projectId: 'authapp-f7d36',
    storageBucket: 'authapp-f7d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZEo3fEODVHNgWCHHkIyabvMo3UUcOtgk',
    appId: '1:696358888242:ios:ac63acfa9cda29b05e6d2b',
    messagingSenderId: '696358888242',
    projectId: 'authapp-f7d36',
    storageBucket: 'authapp-f7d36.firebasestorage.app',
    iosBundleId: 'com.example.projetfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZEo3fEODVHNgWCHHkIyabvMo3UUcOtgk',
    appId: '1:696358888242:ios:ac63acfa9cda29b05e6d2b',
    messagingSenderId: '696358888242',
    projectId: 'authapp-f7d36',
    storageBucket: 'authapp-f7d36.firebasestorage.app',
    iosBundleId: 'com.example.projetfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnaiPY5gRyx_HASt37TyLEbX5U5_6zmWc',
    appId: '1:696358888242:web:93e8d94d9fe369f75e6d2b',
    messagingSenderId: '696358888242',
    projectId: 'authapp-f7d36',
    authDomain: 'authapp-f7d36.firebaseapp.com',
    storageBucket: 'authapp-f7d36.firebasestorage.app',
  );
}
